In [131]:
#imports
import pandas as pd
import numpy as np

In [132]:
df = pd.read_csv('ufc_fighters_statistics2024.csv')
dfAlt = pd.read_csv('alt_fighter_stats2024.csv')

df.head()

,name,nickname,wins,losses,draws,height,weight,reach,stance,dOB,sig_strikes_landed_per_min,sig_striking_accuracy_%,sig_strike_absorbed_per_min,sig_strike_defense(%_of_sig_strikes_not_landed_by_opponent),takedown_average(average_takedown_landed_per_fifteen_min),takedown_accuracy_%,takedown_defense(%_of_opponent_takedown_not_landed),sub_average(average_subs_attempted_per_15_mins)
0,Tom Aaron,NaN,5,3,0,--,155 lbs.,--,NaN,13-Jul-78,0.00,0%,0.00,0%,0.00,0%,0%,0.0
1,Danny Abbadi,The Assassin,4,6,0,"5' 11""",155 lbs.,--,Orthodox,3-Jul-83,3.29,38%,4.41,57%,0.00,0%,77%,0.0
2,Nariman Abbasov,Bayraktar,28,4,0,"5' 8""",155 lbs.,"66""",Orthodox,1-Feb-94,3.00,20%,5.67,46%,0.00,0%,66%,0.0
3,David Abbott,Tank,10,15,0,"6' 0""",265 lbs.,--,Switch,--,1.35,30%,3.55,38%,1.07,33%,66%,0.0
4,Hamdy Abdelwahab,The Hammer,5,0,0 (1 NC),"6' 2""",264 lbs.,"72""",Southpaw,22-Jan-93,3.87,52%,3.13,59%,3.00,75%,0%,0.0

In [133]:
dfAlt.head()

,name,nickname,wins,losses,draws,height,reach,age,nation,sig_str_accuracy,...,takedown_accuracy,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time
0,Danny Abbadi,"""The Assassin""",2.0,2.0,0.0,71.0,NaN,39.0,"Orlando, United States",38%,...,NaN,NaN,3.29,0.00,58%,0.00,4.41,0.00,78%,8:58
1,Nariman Abbassov,NaN,0.0,1.0,0.0,NaN,NaN,29.0,Kazakhstan,20%,...,0%,NaN,3.00,0.00,46%,0.00,5.67,0.00,67%,15:00
2,Tank Abbott,"""Tank""",8.0,10.0,0.0,72.0,NaN,NaN,"Huntington Beach, United States",39%,...,NaN,NaN,2.41,0.00,38%,0.00,10.03,0.00,67%,1:40
3,Hamdy Abdelwahab,"""The Hammer""",5.0,0.0,0.0,74.0,72.0,30.0,Egypt,53%,...,75%,3 of 4,3.87,3.00,59%,1.00,3.13,0.00,NaN,15:00
4,Shamil Abdurakhimov,"""Abrek""",20.0,8.0,0.0,75.0,76.0,41.0,"Dagestan Republic, Russia",44%,...,23%,5 of 30,2.41,1.01,55%,0.29,3.02,0.14,45%,9:27

In [134]:
print(len(df))
print(len(dfAlt))

4112
2713

In [135]:
#clean nicknames in dfAlt
dfAlt['nickname'] = dfAlt['nickname'].str.replace('"', '')

In [136]:
#giving nans characters so dups with nans for nickname cannot match
df['nickname'].fillna('-', inplace=True)
dfAlt['nickname'].fillna('@', inplace=True)

/var/folders/pw/f4_6q0l977bcqprlylly2d1w0000gq/T/ipykernel_2492/3940026178.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['nickname'].fillna('-', inplace=True)
/var/folders/pw/f4_6q0l977bcqprlylly2d1w0000gq/T/ipykernel_2492/3940026178.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfAlt['nickname'].fillna('@', inplace=True)

In [137]:
#outer merge the dfs
dfMerged = pd.merge(df, dfAlt, on=['name', 'nickname'], how='outer', indicator=True)
dfMerged.head()

,name,nickname,wins_x,losses_x,draws_x,height_x,weight,reach_x,stance,dOB,...,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time,_merge
0,AJ Cunningham,The Savage,10.0,3.0,0,"5' 10""",145 lbs.,"71""",Orthodox,7-Sep-94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,AJ Dobson,-,7.0,2.0,0 (1 NC),"6' 1""",185 lbs.,"76""",Orthodox,18-Jan-92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,AJ Dobson,@,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.38,1.82,47%,0.30,5.25,0.30,65%,12:20,right_only
3,AJ Fletcher,The Ghost,10.0,3.0,0,"5' 10""",170 lbs.,"67""",Switch,18-Feb-97,...,4 of 14,3.36,1.54,47%,0.31,4.61,0.93,33%,9:43,both
4,AJ Fonseca,-,5.0,4.0,0,"5' 4""",145 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [138]:
len(dfMerged)

5601

In [139]:
#query dfMerged for intersections
dfMatches = pd.DataFrame(dfMerged.query('_merge == "both"'))
dfMatches.head()

,name,nickname,wins_x,losses_x,draws_x,height_x,weight,reach_x,stance,dOB,...,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time,_merge
3,AJ Fletcher,The Ghost,10.0,3.0,0,"5' 10""",170 lbs.,"67""",Switch,18-Feb-97,...,4 of 14,3.36,1.54,47%,0.31,4.61,0.93,33%,9:43,both
18,Aaron Phillips,The Dragon,12.0,5.0,0,"5' 9""",135 lbs.,"71""",Southpaw,5-Aug-89,...,NaN,1.51,0.86,44%,0.00,3.66,0.57,44%,13:07,both
23,Aaron Simpson,A-Train,12.0,5.0,0,"6' 0""",170 lbs.,"73""",Orthodox,20-Jul-74,...,NaN,3.60,3.78,56%,0.83,2.53,0.47,83%,10:35,both
26,Aaron Wilkinson,The Daywalker,11.0,7.0,0,"5' 10""",155 lbs.,--,Orthodox,31-Jan-87,...,NaN,0.00,7.32,100%,0.00,0.00,0.00,NaN,2:03,both
36,Abel Trujillo,Killa,15.0,8.0,0 (1 NC),"5' 8""",155 lbs.,"70""",Orthodox,18-Sep-83,...,15 of 33,2.65,2.18,60%,0.44,2.31,0.44,40%,9:23,both

In [140]:
print(len(dfMatches))

1224

In [141]:
#query dfMerged for symmetric difference
notMatched = pd.DataFrame(dfMerged.query('_merge != "both"'))
notMatched.head()

,name,nickname,wins_x,losses_x,draws_x,height_x,weight,reach_x,stance,dOB,...,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time,_merge
0,AJ Cunningham,The Savage,10.0,3.0,0,"5' 10""",145 lbs.,"71""",Orthodox,7-Sep-94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,AJ Dobson,-,7.0,2.0,0 (1 NC),"6' 1""",185 lbs.,"76""",Orthodox,18-Jan-92,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
2,AJ Dobson,@,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,4.38,1.82,47%,0.3,5.25,0.3,65%,12:20,right_only
4,AJ Fonseca,-,5.0,4.0,0,"5' 4""",145 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,AJ Matthews,-,8.0,7.0,0,"5' 11""",185 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [142]:
#find the nonMatched items from dfAlt
dfAltNoMatch = pd.merge(notMatched, dfAlt, on=['name', 'nickname'], how='inner')
print(len(dfAltNoMatch))

1491

In [143]:
#find the nonMatched items from df
dfNoMatch = pd.merge(notMatched, df, on=['name', 'nickname'], how='inner')
print(len(dfNoMatch))

2890

In [147]:
#writing non matched instances of both dfs to csv for manual analysis
dfNoMatch.to_csv('SymmetricDifferenceFighterStats.csv', index=False)
dfAltNoMatch.to_csv('SymmetricDifferenceAlt.csv', index=False)