In [1]:
#imports
import pandas as pd
import numpy as np

/var/folders/pw/f4_6q0l977bcqprlylly2d1w0000gq/T/ipykernel_29131/1064896250.py:2: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
df = pd.read_csv('ufc_fighters_statistics2024.csv')
dfAlt = pd.read_csv('alt_fighter_stats2024.csv')

df.head()

,name,nickname,wins,losses,draws,height,weight,reach,stance,dOB,sig_strikes_landed_per_min,sig_striking_accuracy_%,sig_strike_absorbed_per_min,sig_strike_defense(%_of_sig_strikes_not_landed_by_opponent),takedown_average(average_takedown_landed_per_fifteen_min),takedown_accuracy_%,takedown_defense(%_of_opponent_takedown_not_landed),sub_average(average_subs_attempted_per_15_mins)
0,Tom Aaron,NaN,5,3,0,--,155 lbs.,--,NaN,13-Jul-78,0.00,0%,0.00,0%,0.00,0%,0%,0.0
1,Danny Abbadi,The Assassin,4,6,0,"5' 11""",155 lbs.,--,Orthodox,3-Jul-83,3.29,38%,4.41,57%,0.00,0%,77%,0.0
2,Nariman Abbasov,Bayraktar,28,4,0,"5' 8""",155 lbs.,"66""",Orthodox,1-Feb-94,3.00,20%,5.67,46%,0.00,0%,66%,0.0
3,David Abbott,Tank,10,15,0,"6' 0""",265 lbs.,--,Switch,--,1.35,30%,3.55,38%,1.07,33%,66%,0.0
4,Hamdy Abdelwahab,The Hammer,5,0,0 (1 NC),"6' 2""",264 lbs.,"72""",Southpaw,22-Jan-93,3.87,52%,3.13,59%,3.00,75%,0%,0.0

In [3]:
dfAlt.head()

,name,nickname,wins,losses,draws,height,reach,age,nation,sig_str_accuracy,...,takedown_accuracy,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time
0,Danny Abbadi,"""The Assassin""",2.0,2.0,0.0,71.0,NaN,39.0,"Orlando, United States",38%,...,NaN,NaN,3.29,0.00,58%,0.00,4.41,0.00,78%,8:58
1,Nariman Abbassov,NaN,0.0,1.0,0.0,NaN,NaN,29.0,Kazakhstan,20%,...,0%,NaN,3.00,0.00,46%,0.00,5.67,0.00,67%,15:00
2,Tank Abbott,"""Tank""",8.0,10.0,0.0,72.0,NaN,NaN,"Huntington Beach, United States",39%,...,NaN,NaN,2.41,0.00,38%,0.00,10.03,0.00,67%,1:40
3,Hamdy Abdelwahab,"""The Hammer""",5.0,0.0,0.0,74.0,72.0,30.0,Egypt,53%,...,75%,3 of 4,3.87,3.00,59%,1.00,3.13,0.00,NaN,15:00
4,Shamil Abdurakhimov,"""Abrek""",20.0,8.0,0.0,75.0,76.0,41.0,"Dagestan Republic, Russia",44%,...,23%,5 of 30,2.41,1.01,55%,0.29,3.02,0.14,45%,9:27

In [4]:
print(len(df))
print(len(dfAlt))

4112
2713

In [5]:
#clean nicknames in dfAlt
dfAlt['nickname'] = dfAlt['nickname'].str.replace('"', '')

In [6]:
#giving nans characters so dups with nans for nickname cannot match
df['nickname'].fillna('!', inplace=True)
dfAlt['nickname'].fillna('~', inplace=True)

/var/folders/pw/f4_6q0l977bcqprlylly2d1w0000gq/T/ipykernel_29131/1396102374.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['nickname'].fillna('!', inplace=True)
/var/folders/pw/f4_6q0l977bcqprlylly2d1w0000gq/T/ipykernel_29131/1396102374.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  dfAlt['nickname'].fillna('~', inplace=True)

In [7]:
df.head()

,name,nickname,wins,losses,draws,height,weight,reach,stance,dOB,sig_strikes_landed_per_min,sig_striking_accuracy_%,sig_strike_absorbed_per_min,sig_strike_defense(%_of_sig_strikes_not_landed_by_opponent),takedown_average(average_takedown_landed_per_fifteen_min),takedown_accuracy_%,takedown_defense(%_of_opponent_takedown_not_landed),sub_average(average_subs_attempted_per_15_mins)
0,Tom Aaron,!,5,3,0,--,155 lbs.,--,NaN,13-Jul-78,0.00,0%,0.00,0%,0.00,0%,0%,0.0
1,Danny Abbadi,The Assassin,4,6,0,"5' 11""",155 lbs.,--,Orthodox,3-Jul-83,3.29,38%,4.41,57%,0.00,0%,77%,0.0
2,Nariman Abbasov,Bayraktar,28,4,0,"5' 8""",155 lbs.,"66""",Orthodox,1-Feb-94,3.00,20%,5.67,46%,0.00,0%,66%,0.0
3,David Abbott,Tank,10,15,0,"6' 0""",265 lbs.,--,Switch,--,1.35,30%,3.55,38%,1.07,33%,66%,0.0
4,Hamdy Abdelwahab,The Hammer,5,0,0 (1 NC),"6' 2""",264 lbs.,"72""",Southpaw,22-Jan-93,3.87,52%,3.13,59%,3.00,75%,0%,0.0

In [10]:
#find special characters in df
names = (df['name'].values)
nicknames = (df['nickname'].values)

chars2rep = []
for name in names:
    if(isinstance(name, str)):
        for char in name:
            if char.lower() not in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ']:
                chars2rep.append(char)
            if char.upper() not in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', "Q", 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ']:
                chars2rep.append(char)
for nickname in nicknames:
    if(isinstance(nickname, str)):
        for char in nickname:
            if char.lower() not in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ']:
                chars2rep.append(char)
            if char.upper() not in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', "Q", 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ']:
                chars2rep.append(char)


chars2rep = list(set(chars2rep))
for char in chars2rep:
    print(char)

!

In [9]:
#clean name, nickname
for index, row in df.iterrows():
    name = row['name']
    nickname = row['nickname']
    if(isinstance(name, str)):
        cleanName = name.replace('?', '').replace('4', '').replace('9', '').replace('0', '').replace('5', '').replace('7', '').replace('1', '').replace(',', '').replace('3', '').replace('%', '').replace("'", '').replace('-', '').replace('2', '').replace('.', '')
        df.loc[index, 'name'] = cleanName
    if(isinstance(nickname, str)):
        cleanNickname = nickname.replace('?', '').replace('4', '').replace('9', '').replace('0', '').replace('5', '').replace('7', '').replace('1', '').replace(',', '').replace('3', '').replace('%', '').replace("'", '').replace('-', '').replace('2', '').replace('.', '')
        df.loc[index, 'nickname'] = cleanNickname

In [15]:
#find special characters in df
names = (dfAlt['name'].values)
nicknames = (dfAlt['nickname'].values)

chars2rep = []
for name in names:
    if(isinstance(name, str)):
        for char in name:
            if char.lower() not in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ']:
                chars2rep.append(char)
            if char.upper() not in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', "Q", 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ']:
                chars2rep.append(char)
for nickname in nicknames:
    if(isinstance(nickname, str)):
        for char in nickname:
            if char.lower() not in ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', ' ']:
                chars2rep.append(char)
            if char.upper() not in ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', "Q", 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', ' ']:
                chars2rep.append(char)


chars2rep = list(set(chars2rep))
for char in chars2rep:
    print(char)

~

In [14]:
#clean name, nickname
for index, row in dfAlt.iterrows():
    name = row['name']
    nickname = row['nickname']
    if(isinstance(name, str)):
        cleanName = name.replace('2', '').replace('(', '').replace('3', '').replace('ú', 'u').replace('ç', 'c').replace('Á', 'A').replace('7', '').replace('í', 'i').replace('0', '').replace('ě', 'e').replace('4', '').replace("'", '').replace('%', '').replace('"', '').replace('á', 'a').replace(',', '').replace('ć', 'c').replace('ñ', 'n').replace(')', '').replace('ł', 'l').replace('-', '').replace('8', '').replace('ê', 'e').replace('1', '').replace('ę', 'e').replace('5', '').replace('š', '').replace('”', '').replace('ř', 'r').replace('î', 'i').replace('ö', '').replace('ã', 'a').replace('ň', 'n').replace('é', 'e').replace('.', '').replace('“', '')
        dfAlt.loc[index, 'name'] = cleanName
    if(isinstance(nickname, str)):
        cleanNickname = nickname.replace('2', '').replace('(', '').replace('3', '').replace('ú', 'u').replace('ç', 'c').replace('Á', 'A').replace('7', '').replace('í', 'i').replace('0', '').replace('ě', 'e').replace('4', '').replace("'", '').replace('%', '').replace('"', '').replace('á', 'a').replace(',', '').replace('ć', 'c').replace('ñ', 'n').replace(')', '').replace('ł', 'l').replace('-', '').replace('8', '').replace('ê', 'e').replace('1', '').replace('ę', 'e').replace('5', '').replace('š', '').replace('”', '').replace('ř', 'r').replace('î', 'i').replace('ö', '').replace('ã', 'a').replace('ň', 'n').replace('é', 'e').replace('.', '').replace('“', '')
        dfAlt.loc[index, 'nickname'] = cleanNickname

for index, row in dfAlt.iterrows():
    for char in chars2rep:
        name = row['name']
        nickname = row['nickname']
        if(char != '~'):
            if(isinstance(name, str)):
                cleanName = name.replace(char, '')
                dfAlt.loc[index, 'name'] = cleanName
            if(isinstance(nickname, str)):
                cleanNickname = nickname.replace(char, '')
                dfAlt.loc[index, 'nickname'] = cleanNickname

In [16]:
df.iloc[1315:]

,name,nickname,wins,losses,draws,height,weight,reach,stance,dOB,sig_strikes_landed_per_min,sig_striking_accuracy_%,sig_strike_absorbed_per_min,sig_strike_defense(%_of_sig_strikes_not_landed_by_opponent),takedown_average(average_takedown_landed_per_fifteen_min),takedown_accuracy_%,takedown_defense(%_of_opponent_takedown_not_landed),sub_average(average_subs_attempted_per_15_mins)
1315,Akihiro Gono,!,35,21,8,"5' 7""",170 lbs.,"68""",Switch,7-Oct-74,2.18,48%,2.67,63%,1.01,84%,46%,0.5
1316,Gabriel Gonzaga,Napao,17,11,0,"6' 2""",242 lbs.,"76""",Orthodox,18-May-79,2.12,45%,2.94,57%,2.80,39%,66%,1.1
1317,Justin Gonzales,JTrain,6,0,0,"5' 9""",145 lbs.,"72""",Orthodox,28-Apr-91,6.67,80%,0.87,43%,14.00,73%,100%,0.0
1318,Fernando Gonzalez,The Menifee Maniac,26,14,0,"5' 9""",170 lbs.,"68""",Southpaw,15-Sep-83,4.47,47%,4.03,65%,0.86,33%,43%,1.4
1319,Nick Gonzalez,The Ghost,17,12,0 (1 NC),"5' 6""",155 lbs.,--,Orthodox,3-Mar-81,0.59,20%,2.35,33%,0.00,0%,50%,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4107,Dave Zitanick,!,5,7,0 (1 NC),--,170 lbs.,--,NaN,5-Mar-80,0.00,0%,0.00,0%,0.00,0%,0%,0.0
4108,Alex Zuniga,!,6,3,0,--,145 lbs.,--,NaN,--,0.00,0%,0.00,0%,0.00,0%,0%,0.0
4109,George Zuniga,!,3,1,0,"5' 9""",185 lbs.,--,NaN,--,7.64,38%,5.45,37%,0.00,0%,100%,0.0
4110,Allan Zuniga,Tigre,13,1,0,"5' 7""",155 lbs.,"70""",Orthodox,4-Apr-92,3.93,52%,1.80,61%,0.00,0%,57%,1.0
4111,Virgil Zwicker,RezDog,15,6,1,"6' 2""",205 lbs.,"74""",NaN,26-Jun-82,3.34,48%,4.87,39%,1.31,30%,50%,0.0

In [17]:
dfAlt.iloc[945:]

,name,nickname,wins,losses,draws,height,reach,age,nation,sig_str_accuracy,...,takedown_accuracy,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time
945,Akihiro Gono,The Japanese Sensation,28.0,14.0,7.0,69.0,NaN,48.0,United States,53%,...,80%,NaN,2.35,1.57,64%,0.39,11.35,0.39,46%,12:46
946,Gabriel Gonzaga,Napao,17.0,11.0,0.0,74.0,76.0,44.0,"Rio De Janeiro, Brazil",45%,...,39%,NaN,2.12,2.80,57%,0.70,2.94,1.10,67%,6:31
947,Justin Gonzales,JTrain,9.0,0.0,0.0,69.0,NaN,32.0,"Denver, United States",80%,...,74%,NaN,6.67,14.00,43%,0.00,0.87,0.00,100%,15:00
948,Pearl Gonzalez,~,6.0,2.0,0.0,64.5,68.0,36.0,"Chicago, United States",38%,...,11%,2 of 18,2.23,1.04,57%,0.00,4.07,0.52,NaN,14:23
949,Jason Gonzalez,Nicoya,11.0,5.0,0.0,74.0,74.0,33.0,"Torrance, United States",40%,...,NaN,NaN,3.06,0.00,59%,0.00,3.13,1.00,30%,3:46
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2708,Yi Zha,~,23.0,4.0,0.0,67.0,70.5,26.0,"Aba Sichuan, China",43%,...,35%,5 of 46,2.74,4.83,52%,0.00,2.15,1.21,62%,9:56
2709,Tiequan Zhang,The Wolf,18.0,4.0,0.0,68.0,NaN,44.0,"Nei, Mongolia",36%,...,58%,2 of 12,1.23,1.95,52%,0.00,2.14,3.35,75%,8:58
2710,Zhang Weili,Magnum,24.0,3.0,0.0,64.0,63.0,34.0,"Hebei, China",52%,...,42%,1 of 45,5.94,2.29,54%,0.36,3.44,0.36,67%,12:25
2711,Daermisi Zhawupasi,~,1.0,1.0,0.0,NaN,NaN,23.0,China,0%,...,NaN,NaN,0.00,0.00,100%,0.00,0.00,15.52,NaN,7:17
2712,Dariya Zheleznykova,~,0.0,0.0,0.0,NaN,NaN,27.0,NaN,0%,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0:00

In [18]:
#assign nicknames for matching names found withink dataframes
count = 1
for index, row in df.iterrows():
    name = row['name']
    nickname = row['nickname']
    dup_check = df.loc[df['name'] == name]
    dup_check2 = dfAlt.loc[dfAlt['name'] == name]
    if(len(dup_check == 1) and len(dup_check2) == 1):
        try:
            altIndex = dfAlt.loc[dfAlt['name'] == name].index[0]
            altNickname = dfAlt.loc[altIndex, 'nickname']
            if(nickname != altNickname):
                if(nickname == '!' and altNickname == '~'):
                    df.loc[index, 'nickname'] = str(count)
                    dfAlt.loc[altIndex, 'nickname'] = str(count)
                    count+=1
                elif(nickname != '!'):
                    dfAlt.loc[altIndex, 'nickname'] = nickname
                elif(altNickname != '~'):
                    df.loc[index, 'nickname'] = altNickname
        except:
            pass

In [19]:
#outer merge the dfs
dfMerged = pd.merge(df, dfAlt, on=['name', 'nickname'], how='outer', indicator=True)
dfMerged.head()

,name,nickname,wins_x,losses_x,draws_x,height_x,weight,reach_x,stance,dOB,...,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time,_merge
0,AJ Cunningham,The Savage,10.0,3.0,0,"5' 10""",145 lbs.,"71""",Orthodox,7-Sep-94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
1,AJ Dobson,180,7.0,2.0,0 (1 NC),"6' 1""",185 lbs.,"76""",Orthodox,18-Jan-92,...,NaN,4.38,1.82,47%,0.30,5.25,0.30,65%,12:20,both
2,AJ Fletcher,The Ghost,10.0,3.0,0,"5' 10""",170 lbs.,"67""",Switch,18-Feb-97,...,4 of 14,3.36,1.54,47%,0.31,4.61,0.93,33%,9:43,both
3,AJ Fonseca,!,5.0,4.0,0,"5' 4""",145 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,AJ Matthews,!,8.0,7.0,0,"5' 11""",185 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [20]:
len(dfMerged)

4302

In [21]:
#query dfMerged for intersections
dfMatches = pd.DataFrame(dfMerged.query('_merge == "both"'))
dfMatches.head()

,name,nickname,wins_x,losses_x,draws_x,height_x,weight,reach_x,stance,dOB,...,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time,_merge
1,AJ Dobson,180,7.0,2.0,0 (1 NC),"6' 1""",185 lbs.,"76""",Orthodox,18-Jan-92,...,NaN,4.38,1.82,47%,0.30,5.25,0.30,65%,12:20,both
2,AJ Fletcher,The Ghost,10.0,3.0,0,"5' 10""",170 lbs.,"67""",Switch,18-Feb-97,...,4 of 14,3.36,1.54,47%,0.31,4.61,0.93,33%,9:43,both
7,Aalon Cruz,146,8.0,4.0,0,"6' 0""",145 lbs.,"78""",Switch,20-Sep-89,...,NaN,7.58,0.00,59%,0.85,8.88,0.00,NaN,5:54,both
8,Aaron Brink,95,26.0,26.0,0 (2 NC),"6' 3""",205 lbs.,--,Orthodox,12-Nov-74,...,NaN,0.00,0.00,57%,0.00,19.64,0.00,NaN,0:55,both
10,Aaron Jeffery,345,10.0,3.0,0,"6' 2""",185 lbs.,"73""",Orthodox,14-Nov-92,...,NaN,3.10,0.00,34%,0.00,4.46,0.00,50%,9:12,both

In [22]:
print(len(dfMatches))

2525

In [23]:
#query dfMerged for symmetric difference
notMatched = pd.DataFrame(dfMerged.query('_merge != "both"'))
notMatched.head()

,name,nickname,wins_x,losses_x,draws_x,height_x,weight,reach_x,stance,dOB,...,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time,_merge
0,AJ Cunningham,The Savage,10.0,3.0,0,"5' 10""",145 lbs.,"71""",Orthodox,7-Sep-94,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
3,AJ Fonseca,!,5.0,4.0,0,"5' 4""",145 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
4,AJ Matthews,!,8.0,7.0,0,"5' 11""",185 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
5,AJ McKee,Mercenary,8.0,0.0,0,"5' 10""",145 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
6,AJ Siscoe,Lets Go,1.0,2.0,0,"5' 7""",135 lbs.,--,NaN,--,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [24]:
#find the nonMatched items from dfAlt
dfAltNoMatch = pd.merge(notMatched, dfAlt, on=['name', 'nickname'], how='inner')
print(len(dfAltNoMatch))

192

In [25]:
#find the nonMatched items from df
dfNoMatch = pd.merge(notMatched, df, on=['name', 'nickname'], how='inner')
print(len(dfNoMatch))

1587

In [27]:
#writing non matched instances of both dfs to csv for manual analysis
dfNoMatch.to_csv('SymmetricDifferenceFighterStats.csv', index=False)
dfAltNoMatch.to_csv('SymmetricDifferenceAlt.csv', index=False)

In [54]:
result_df = df.loc[df['name'] == 'Alessandro Ricci']
result_df.head()

,name,nickname,wins,losses,draws,height,weight,reach,stance,dOB,sig_strikes_landed_per_min,sig_striking_accuracy_%,sig_strike_absorbed_per_min,sig_strike_defense(%_of_sig_strikes_not_landed_by_opponent),takedown_average(average_takedown_landed_per_fifteen_min),takedown_accuracy_%,takedown_defense(%_of_opponent_takedown_not_landed),sub_average(average_subs_attempted_per_15_mins),nickame
3060,Alessandro Ricci,5000,10,5,0,"5' 11""",155 lbs.,--,Orthodox,21-Jul-82,2.48,41%,2.53,64%,0.0,0%,64%,0.0,NaN

In [53]:
result_df2 = dfAlt.loc[dfAlt['name'] == 'Alessandro Ricci']
result_df2.head()

,name,nickname,wins,losses,draws,height,reach,age,nation,sig_str_accuracy,...,takedown_accuracy,takedown_totals,sig_str_per_minute,takedown_avg_per_fifteen,sig_str_defense,knockdown_avg,sig_str_absorbed_per_min,submission_avg_per_fifteen,takedown_defense,avg_fight_time
1983,Alessandro Ricci,5000,10.0,5.0,0.0,71.0,69.0,40.0,"Toronto, Canada",41%,...,0%,NaN,2.48,0.0,65%,0.0,2.53,0.0,64%,9:52

In [52]:
#fixing inconsistencies to allow intersection query to find more matches
df.at[3060, 'name'] = 'Alessandro Ricci'
df.at[3060, 'nickname'] = '5000'
dfAlt.at[1983, 'nickname'] = '5000'


df.at[3783, 'name'] = 'Alberto Pereira'
df.at[3783, 'nickname'] = 'Uda'

dfAlt.at[833, 'name'] = 'Acacio Dos Santos'
dfAlt.at[833, 'nickname'] = 'Pequeno'